package forge

import (
	"fmt"
)

func Test() error {
	fmt.Println("Forge test executed Successfully")
	return nil
} 
